CREATE TABLE order_details (
    id INT8 GENERATED BY DEFAULT AS IDENTITY,
    amount INT4,
    total FLOAT8,
    order_id INT8,
    PRIMARY KEY (id));
CREATE TABLE orders (
    id INT8 GENERATED BY DEFAULT AS IDENTITY,
    user_id INT8,
    PRIMARY KEY (id));
CREATE TABLE products (
    id INT8 GENERATED BY DEFAULT AS IDENTITY,
    barcode INT4,
    name VARCHAR(255),
    price FLOAT8,
    order_details_id INT8,
    PRIMARY KEY (id));
CREATE TABLE users (
    id INT8 GENERATED BY DEFAULT AS IDENTITY,
    created_date DATE,
    address VARCHAR(255),
    age INT2,
    image VARCHAR(255),
    name VARCHAR(255),
    phone_number VARCHAR(255),
    surname VARCHAR(255),
    password varchar(255),
    role varchar(255),
    updated_date DATE,
    username VARCHAR(255),
    PRIMARY KEY (id));
ALTER TABLE IF EXISTS users
    ADD CONSTRAINT username UNIQUE (username);
ALTER TABLE IF EXISTS order_details
    ADD CONSTRAINT orders_id FOREIGN KEY (order_id) REFERENCES orders;
ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT users_id FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE IF EXISTS products
    ADD CONSTRAINT order_details_id FOREIGN KEY (order_details_id) REFERENCES order_details;
